### ISSUE TITLE
License violations

### ISSUE THREAD

**Issue by Scimmia22** [liberodark/Chromium-Codecs#1]
This distributes 2 binaries. ffmpeg is under the GPL and requires you provide the source and build scripts that it was built from. Where are they? The widevine plugin is not redistributable without a separate license from Google. Do you have that?

**Comment by liberodark** [comment]
Have two sources is Google and Ubuntu !
No many more licence you have possibility to add this for me i use firefox or chrome.
This project is for help linux users you can add licence.

**Comment by Scimmia22** [comment]
When you're violating every license involved by doing what you're doing, it's not about "adding" licenses, it means one thing:

THIS ENTIRE REPOS IS ILLEGAL

**Comment by liberodark** [comment]
Im go to fix that

**Comment by dnewgard** [comment]
Closing this while continuing to illegally distribute binaries does not make this any less illegal
